### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by gmat224** [UoaWDCC/auis-portal#22]
### Description
As a non-member mobile and desktop user, I want to see the footer so that I can find social media and contact information.

### Acceptance Criteria
- [ ] Figma design approved 
- [ ] All links work and re-direct the user to the correct pages
- [ ] Styling complete
- [ ] Accessibility taken into account
- [ ] Documentation complete
- [ ] Test cases written
- [ ] Social media links work
- [ ] Contact Information provided
- [ ] Resizes when going from large screen to small screen

**Comment by nroh555** [comment]
Done
