### ISSUE TITLE
Hamburger Menu for Navigation bar

### ISSUE THREAD

**Issue by gmat224** [UoaWDCC/auis-portal#28]
### Description
As a mobile user, I want to access the links on the navbar so that I can go to a different page on the website.

### Acceptance Criteria
- [ ] Figma design approved 
- [ ] All links work and re-direct the user to the correct pages
- [ ] Styling complete
- [ ] Accessibility taken into account
- [ ] Documentation complete
- [ ] Test cases written

**Comment by nroh555** [comment]
Done
